debug: true

security:
  oauth2:
    sso:
      login-path: /login
    client:
      client-id: test-client-id
      client-secret: test-client-id-secret-123
      access-token-uri: http://localhost:8082/security/oauth/token
      user-authorization-uri: http://localhost:8082/security/oauth/authorize
#      clientAuthenticationScheme: form
    resource:
#      userInfoUri: http://localhost:8082/me
      token-info-uri: http://localhost:8082/security/oauth/check_token
      prefer-token-info: true
      
logging:
  level:
    org.springframework.security: DEBUG